name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{matrix.os}}
    env: 
      FEED_URL: https://nuget.pkg.github.com/${{github.repository_owner}}/index.json

    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683       # v4.2.2
      with:
        submodules: true

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@802fa1a2c4e212495c05bf94dba2704a92a472be # v2.0.2
      with:
        cmake-version: '3.31'

    - name: Run Workflow
      run: |
        cmake --version
        cmake --workflow --preset default
